### ISSUE TITLE
Modify helm charts to make consistent with operator

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8-controller#109]
Identify some consistent naming between the analytic engine and the controller and use the same names in helm charts as well. Also structure of helm charts is different and labels too. Try to make more consistent.
Add any needed configurations not already present like port for controller.

**Comment by kalantar** [comment]
@fabolive Should I remove the knative helm charts in iter8-analytics as part of this PR? I don't recall if we want them gone in 0.1.1 or just 1.0.0

**Comment by fabolive** [comment]
@kalantar: Let's fix everything even for 0.1.1.
