### ISSUE TITLE
Discuss need to add "metrics" as a drop down box in the Grafana dashboard

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8-controller#110]
I'm adding a Grafana dashboard for Iter8-trend, and I noticed that some Experiments could have multiple metrics defined in the success criteria. So, I added a drop down box in the Iter8-trend dashboard so users choose one to visualize. 

In the main Iter8 dashboard, instead of having a 'metrics' drop down option, we have a window for http latency, one for error count, and another for error rate. As we now use Kui to ease the creation of custom metrics, it would good to revisit this dashboard design to allow custom metrics to be visualized as well.

cc @fabolive

**Comment by fabolive** [comment]
cc: @sriumcp

**Comment by huang195** [comment]
Just to clarify and capture an earlier verbal discussion here: The main concern I have about adding the drop down box now is sometimes a user would like to see multiple metrics simultaneously instead of 1 by 1. However, another idea is to add multiple metric drop down boxes, e.g., metric1, metric2, metric3. Each metric will be displayed in its own panel. This allows the dashboard to be simplified, yet multiple metrics to be viewed at the same time. However, this also sets the maximum number of metrics user can view at once.

**Comment by huang195** [comment]
OK, after working on iter8-trend dashboard, I came to realize that there's a key difference from our main iter8 dashboard. In iter8-trend dashboard, we are displaying data from Prometheus that is already curated by the iter8-trend backend, thus all Prometheus queries for different metrics are exactly the same except the qualifier name, e.g., metric='cpu', metric='mem', etc. For the metrics in the main dashboard, these are raw data directly from Prometheus. They cannot be simply queried by changing a qualifier field, but requires different Prometheus queries. 

For now, I'm closing this issue. I think it's sufficient for now to keep all the metrics on the dashboard. User would probably need to modify the dashboard for their custom metrics anyways.
