### ISSUE TITLE
Grafana dashboard not showing any resource utilization anymore

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8-controller#120]
I don't know if it's just me or Grafana's dashboard that used to show resource utilization is no longer showing any data. @fabolive @sriumcp can you look at your environment and confirm if this is reproducible in your environment?

**Comment by huang195** [comment]
Besides not showing up in the dashboard, something seems to be wrong with the Grafana queries for resource utilization. As an example, I queried for CPU utilization for `reviews-v2`. It returned 4 rows of data: i) pause container, ii) istio-proxy container, iii) reviews container, and iv) total for the entire pod. The current query filters out i) and ii), but sums up iii) and iv). This seems to be double counting.

**Comment by huang195** [comment]
It looks like memory utilization query is also not correct. The CPU query is:
```
sum(rate(container_cpu_usage_seconds_total{pod_name=~"$baseline.*", container_name!~"istio-proxy", namespace="$namespace"}[$window_size]))
```
And the memory query is
```
sum(rate(container_memory_working_set_bytes{pod_name=~"$baseline.*", container_name!~"istio-proxy", namespace="$namespace"}[$window_size]))
```
`container_cpu_usage_seconds_total` is a cumulative time series, so it makes sense to use `sum()` and `rate()`. However, `container_memory_working_set_bytes` is a gauge type of cumulative time series. It doesn't seem to make sense to me to use the same `sum()` and `rate()` functions on it. I'm not sure if my understanding is correct.

**Comment by fabolive** [comment]
As per our discussions, the problem here is that, since K8s 1.16 the utilization metrics are reported with different labels for container and pod names. We need to take that into account when telling the user how to populate Grafana with the iter8 dashboard template. Specifically, we need templates covering the following:

- Istio telemetry version -- v1 and v2;
- Kubernetes version -- before 1.16 and from 1.16 on.

**Comment by fabolive** [comment]
@sriumcp: @huang195's understanding of our memory utilization query in our Grafana dashboard indicates that our query is incorrect. Do you agree with his observation?

**Comment by fabolive** [comment]
I will use this issue to fix the label name problems, and will create another one if @sriumcp concurs with @huang195.

**Comment by sriumcp** [comment]
@huang195 I agree with your assessment of double counting.

If you have alternative suggestions for the resource utilization queries in Grafana, we can definitely work with those.

**Comment by huang195** [comment]
For CPU, I use: https://github.com/iter8-tools/iter8-trend/blob/master/iter8-trend.py#L229
For Memory, I use: https://github.com/iter8-tools/iter8-trend/blob/master/iter8-trend.py#L233

**Comment by huang195** [comment]
Disk Read: https://github.com/iter8-tools/iter8-trend/blob/master/iter8-trend.py#L240
Disk Write: https://github.com/iter8-tools/iter8-trend/blob/master/iter8-trend.py#L244
Network Read: https://github.com/iter8-tools/iter8-trend/blob/master/iter8-trend.py#L248
Network Write: https://github.com/iter8-tools/iter8-trend/blob/master/iter8-trend.py#L252

These are similar to CPU query as they use `*_total` type of metrics, but we need to add `image=~".+"` qualifier to exclude the pod itself to prevent double counting.
