### ISSUE TITLE
Merge current code base into master

### ISSUE THREAD

**Issue by Alan-Cha** [iter8-tools/iter8-controller#211]

**Comment by kalantar** [comment]
current code is in fork/branch kalantar/controller-v1.0.0-mk

**Comment by kalantar** [comment]
The code is currently able to be merged with master but will probably break all the tests

**Comment by kalantar** [comment]
This was completed via https://github.com/iter8-tools/iter8-controller/pulls/221 and https://github.com/iter8-tools/iter8-controller/pulls/229.
