### ISSUE TITLE
Problems with Istio 1.4

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8-controller#52]
Trafffic splitting fails when using Istio 1.4

The problem seems to be that we are creating virtualservices with `port: {}`. This causes Istio to look for `host:0`.

**Comment by kalantar** [comment]
By hand we verified the behavior we want works if we leave out the port field; it is optional.

**Comment by kalantar** [comment]
We seem to be using an old library: github.com/knative/pkg/apis/istio/v1alpha3 to define the VirtualServices. This requires the port field.
We need to update to use a new library such as https://github.com/istio/client-go

**Comment by esnible** [comment]
Related discussion: https://github.com/istio/istio/issues/19271

A PR will make the VirtualServices created by the current Iter8 invalid: https://github.com/istio/istio/pull/19351

Note that the linked Istio issue suggests setting traffic to 0%, as iter8 does, is not valid.  I believe that comment is incorrect.  We may need to get an official ruling.

**Comment by kimikowang** [comment]
fixed in https://github.com/iter8-tools/iter8-controller/pull/59
