### ISSUE TITLE
Refactor the code to that calls iter8-analytics in light of multiple algorithms

### ISSUE THREAD

**Issue by fabolive** [iter8-tools/iter8-controller#63]

**Comment by kimikowang** [comment]
https://github.com/iter8-tools/iter8-controller/pull/64

So far new analytics algorithms may require changes in input to TrafficControl and SuccessCriterion. Convert their static struct to type map[string]interface{} so that new parameters can be added flexibly.

**Comment by fabolive** [comment]
@kimikowang: Can this issue be closed?
