### ISSUE TITLE
Change crd and controller-code to support new version assessment and traffic split algorithms

### ISSUE THREAD

**Issue by kimikowang** [iter8-tools/iter8-controller#85]

**Comment by sriumcp** [comment]
New CRD changes will support the following features for iter8 end-users.

1. Canary release with 2 versions (in 0.1.0) with 7 distinct existing algorithms (Unif / PBR / OBR / epsilon greedy algos / check and increment / Top-2 PBR / Top-2 OBR)
2. A/B testing with reward with 2 versions (PBR / OBR / epsilon greedy algos / check and increment)
3. Version insights -- probability of a version being the winner. Probability of the version meeting the success criteria. If we focus on a particular metric alone, probability of a version being the best version (computed using Bayesian approaches)
4. Simplify iter8 metric definitions
